services:
  - type: web
    name: medical-rag-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn rag_api:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: COHERE_API_KEY
        sync: false
